




const PATIENT: &[Membership] = &[
    itself("Patient", &["link"]),
    gathers("Account", &["subject"]),
    gathers("AdverseEvent", &["subject"]),
    gathers("AllergyIntolerance", &["asserter", "participant", "patient", "recorder"]),
    gathers("Appointment", &["actor"]),
    gathers("AppointmentResponse", &["actor"]),
    gathers("AuditEvent", &["agent.patient", "entity.patient", "patient"]),
    gathers("Basic", &["author", "patient"]),
    gathers("BiologicallyDerivedProductDispense", &["patient"]),
    gathers("BodySite", &["patient"]),
    gathers("BodyStructure", &["patient"]),
    gathers("CarePlan", &["patient", "performer"]),
    gathers("CareTeam", &["participant", "patient"]),
    gathers("ChargeItem", &["subject"]),
    gathers("Claim", &["patient", "payee"]),
    gathers("ClaimResponse", &["patient"]),
    gathers("ClinicalImpression", &["subject"]),
    gathers("Communication", &["recipient", "sender", "subject"]),
    gathers("CommunicationRequest", &["information-provider", "recipient", "requester", "sender", "subject"]),
    gathers("Composition", &["attester", "author", "subject"]),
    gathers("Condition", &["asserter", "participant-actor", "patient"]),
    gathers("Consent", &["patient", "subject"]),
    gathers("Contract", &["patient"]),
    gathers("Coverage", &["beneficiary", "paymentby-party", "payor", "policy-holder", "subscriber"]),
    gathers("CoverageEligibilityRequest", &["patient"]),
    gathers("CoverageEligibilityResponse", &["patient"]),
    gathers("DetectedIssue", &["patient"]),
    gathers("DeviceAssociation", &["operator", "subject"]),
    gathers("DeviceRequest", &["performer", "requester", "subject"]),
    gathers("DeviceUsage", &["patient"]),
    gathers("DeviceUseStatement", &["subject"]),
    gathers("DiagnosticReport", &["subject"]),
    gathers("DocumentManifest", &["author", "recipient", "subject"]),
    gathers("DocumentReference", &["author", "subject"]),
    gathers("EligibilityRequest", &["patient"]),
    gathers("Encounter", &["patient"]),
    gathers("EncounterHistory", &["patient"]),
    gathers("EnrollmentRequest", &["subject"]),
    gathers("EpisodeOfCare", &["patient"]),
    gathers("ExplanationOfBenefit", &["patient", "payee"]),
    gathers("FamilyMemberHistory", &["patient"]),
    gathers("Flag", &["patient"]),
    gathers("GenomicStudy", &["patient"]),
    gathers("Goal", &["patient"]),
    gathers("Group", &["member"]),
    gathers("GuidanceResponse", &["patient"]),
    gathers("ImagingManifest", &["author", "patient"]),
    gathers("ImagingSelection", &["patient"]),
    gathers("ImagingStudy", &["patient"]),
    gathers("Immunization", &["patient"]),
    gathers("ImmunizationEvaluation", &["patient"]),
    gathers("ImmunizationRecommendation", &["patient"]),
    gathers("Invoice", &["patient", "recipient", "subject"]),
    gathers("List", &["source", "subject"]),
    gathers("MeasureReport", &["patient"]),
    gathers("Media", &["subject"]),
    gathers("MedicationAdministration", &["patient", "performer", "subject"]),
    gathers("MedicationDispense", &["patient", "receiver", "subject"]),
    gathers("MedicationRequest", &["subject"]),
    gathers("MedicationStatement", &["subject"]),
    gathers("MolecularSequence", &["patient", "subject"]),
    gathers("NutritionIntake", &["source", "subject"]),
    gathers("NutritionOrder", &["patient"]),
    gathers("Observation", &["performer", "subject"]),
    gathers("Person", &["patient"]),
    gathers("Procedure", &["patient", "performer"]),
    gathers("ProcedureRequest", &["performer", "subject"]),
    gathers("Provenance", &["patient", "target.patient", "target.subject"]),
    gathers("QuestionnaireResponse", &["author", "subject"]),
    gathers("ReferralRequest", &["patient", "requester"]),
    gathers("RelatedPerson", &["patient"]),
    gathers("RequestGroup", &["participant", "subject"]),
    gathers("RequestOrchestration", &["participant", "subject"]),
    gathers("ResearchSubject", &["individual", "subject"]),
    gathers("RiskAssessment", &["subject"]),
    gathers("Schedule", &["actor"]),
    gathers("ServiceRequest", &["performer", "subject"]),
    gathers("Specimen", &["subject"]),
    gathers("SupplyDelivery", &["patient"]),
    gathers("SupplyRequest", &["requester", "subject"]),
    gathers("Task", &["focus", "patient"]),
    gathers("VisionPrescription", &["patient"]),
];

const ENCOUNTER: &[Membership] = &[
    itself("Encounter", &[]),
    gathers("CarePlan", &["encounter"]),
    gathers("CareTeam", &["encounter"]),
    gathers("ChargeItem", &["context", "encounter"]),
    gathers("Claim", &["encounter"]),
    gathers("ClinicalImpression", &["context", "encounter"]),
    gathers("Communication", &["context", "encounter"]),
    gathers("CommunicationRequest", &["context", "encounter"]),
    gathers("Composition", &["encounter"]),
    gathers("Condition", &["context", "encounter"]),
    gathers("DeviceRequest", &["encounter"]),
    gathers("DiagnosticReport", &["encounter"]),
    gathers("DocumentManifest", &["related-ref"]),
    gathers("DocumentReference", &["context", "encounter"]),
    gathers("EncounterHistory", &["encounter"]),
    gathers("ExplanationOfBenefit", &["encounter"]),
    gathers("Media", &["encounter"]),
    gathers("MedicationAdministration", &["context", "encounter"]),
    gathers("MedicationDispense", &["encounter"]),
    gathers("MedicationRequest", &["context", "encounter"]),
    gathers("MedicationStatement", &["encounter"]),
    gathers("NutritionIntake", &["encounter"]),
    gathers("NutritionOrder", &["encounter"]),
    gathers("Observation", &["encounter"]),
    gathers("Procedure", &["encounter"]),
    gathers("ProcedureRequest", &["context"]),
    gathers("QuestionnaireResponse", &["context", "encounter"]),
    gathers("RequestGroup", &["encounter"]),
    gathers("RequestOrchestration", &["encounter"]),
    gathers("ServiceRequest", &["encounter"]),
    gathers("VisionPrescription", &["encounter"]),
];

const RELATEDPERSON: &[Membership] = &[
    itself("RelatedPerson", &[]),
    gathers("AdverseEvent", &["recorder"]),
    gathers("AllergyIntolerance", &["asserter", "participant"]),
    gathers("Appointment", &["actor"]),
    gathers("AppointmentResponse", &["actor"]),
    gathers("Basic", &["author"]),
    gathers("CarePlan", &["performer"]),
    gathers("CareTeam", &["participant"]),
    gathers("ChargeItem", &["enterer", "participant-actor", "performer-actor"]),
    gathers("Claim", &["payee"]),
    gathers("Communication", &["recipient", "sender"]),
    gathers("CommunicationRequest", &["information-provider", "recipient", "requester", "sender"]),
    gathers("Composition", &["author"]),
    gathers("Condition", &["asserter", "participant-actor"]),
    gathers("Coverage", &["paymentby-party", "payor", "policy-holder", "subscriber"]),
    gathers("DocumentManifest", &["author", "recipient"]),
    gathers("DocumentReference", &["author"]),
    gathers("Encounter", &["participant"]),
    gathers("ExplanationOfBenefit", &["payee"]),
    gathers("ImagingManifest", &["author"]),
    gathers("Invoice", &["recipient"]),
    gathers("MedicationAdministration", &["performer"]),
    gathers("MedicationStatement", &["source"]),
    gathers("NutritionIntake", &["source"]),
    gathers("Observation", &["performer"]),
    gathers("Patient", &["link"]),
    gathers("Person", &["link"]),
    gathers("Procedure", &["performer"]),
    gathers("ProcedureRequest", &["performer"]),
    gathers("Provenance", &["agent"]),
    gathers("QuestionnaireResponse", &["author", "source"]),
    gathers("RequestGroup", &["participant"]),
    gathers("RequestOrchestration", &["participant"]),
    gathers("Schedule", &["actor"]),
    gathers("ServiceRequest", &["performer"]),
    gathers("SupplyRequest", &["requester"]),
];

const PRACTITIONER: &[Membership] = &[
    itself("Practitioner", &[]),
    gathers("Account", &["subject"]),
    gathers("AdverseEvent", &["recorder"]),
    gathers("AllergyIntolerance", &["asserter", "participant", "recorder"]),
    gathers("Appointment", &["actor"]),
    gathers("AppointmentResponse", &["actor"]),
    gathers("AuditEvent", &["agent"]),
    gathers("Basic", &["author"]),
    gathers("BiologicallyDerivedProductDispense", &["performer"]),
    gathers("CarePlan", &["performer"]),
    gathers("CareTeam", &["participant"]),
    gathers("ChargeItem", &["enterer", "participant-actor", "performer-actor"]),
    gathers("Claim", &["care-team", "enterer", "payee", "provider"]),
    gathers("ClaimResponse", &["request-provider", "requestor"]),
    gathers("ClinicalImpression", &["assessor", "performer"]),
    gathers("Communication", &["recipient", "sender"]),
    gathers("CommunicationRequest", &["information-provider", "recipient", "requester", "sender"]),
    gathers("Composition", &["attester", "author", "subject"]),
    gathers("Condition", &["asserter", "participant-actor"]),
    gathers("CoverageEligibilityRequest", &["enterer", "provider"]),
    gathers("CoverageEligibilityResponse", &["requestor"]),
    gathers("DetectedIssue", &["author"]),
    gathers("DeviceAssociation", &["operator"]),
    gathers("DeviceRequest", &["performer", "requester"]),
    gathers("DiagnosticReport", &["performer"]),
    gathers("DocumentManifest", &["author", "recipient", "subject"]),
    gathers("DocumentReference", &["attester", "authenticator", "author", "subject"]),
    gathers("EligibilityRequest", &["enterer", "provider"]),
    gathers("EligibilityResponse", &["request-provider"]),
    gathers("Encounter", &["participant", "practitioner"]),
    gathers("EpisodeOfCare", &["care-manager"]),
    gathers("ExplanationOfBenefit", &["care-team", "enterer", "payee", "provider"]),
    gathers("Flag", &["author"]),
    gathers("Group", &["member"]),
    gathers("ImagingManifest", &["author"]),
    gathers("Immunization", &["performer", "practitioner"]),
    gathers("Invoice", &["participant"]),
    gathers("Linkage", &["author"]),
    gathers("List", &["source"]),
    gathers("Media", &["operator", "subject"]),
    gathers("MedicationAdministration", &["performer"]),
    gathers("MedicationDispense", &["performer", "receiver"]),
    gathers("MedicationRequest", &["requester"]),
    gathers("MedicationStatement", &["source"]),
    gathers("MessageHeader", &["author", "enterer", "receiver", "responsible"]),
    gathers("NutritionIntake", &["source"]),
    gathers("NutritionOrder", &["provider"]),
    gathers("Observation", &["performer"]),
    gathers("Patient", &["general-practitioner"]),
    gathers("PaymentNotice", &["provider", "reporter"]),
    gathers("PaymentReconciliation", &["request-provider", "requestor"]),
    gathers("Person", &["practitioner"]),
    gathers("PractitionerRole", &["practitioner"]),
    gathers("Procedure", &["performer"]),
    gathers("ProcedureRequest", &["performer", "requester"]),
    gathers("ProcessRequest", &["provider"]),
    gathers("ProcessResponse", &["request-provider"]),
    gathers("Provenance", &["agent"]),
    gathers("QuestionnaireResponse", &["author", "source"]),
    gathers("ReferralRequest", &["recipient", "requester"]),
    gathers("RequestGroup", &["author", "participant"]),
    gathers("RequestOrchestration", &["author", "participant"]),
    gathers("ResearchStudy", &["principalinvestigator"]),
    gathers("RiskAssessment", &["performer"]),
    gathers("Schedule", &["actor"]),
    gathers("ServiceRequest", &["performer", "requester"]),
    gathers("Specimen", &["collector"]),
    gathers("SupplyDelivery", &["receiver", "supplier"]),
    gathers("SupplyRequest", &["requester"]),
    gathers("VisionPrescription", &["prescriber"]),
];

const DEVICE: &[Membership] = &[
    itself("Device", &[]),
    gathers("Account", &["subject"]),
    gathers("Appointment", &["actor"]),
    gathers("AppointmentResponse", &["actor"]),
    gathers("AuditEvent", &["agent"]),
    gathers("ChargeItem", &["enterer", "participant-actor", "performer-actor"]),
    gathers("Claim", &["detail-udi", "item-udi", "procedure-udi", "subdetail-udi"]),
    gathers("Communication", &["recipient", "sender"]),
    gathers("CommunicationRequest", &["information-provider", "recipient", "sender"]),
    gathers("Composition", &["author"]),
    gathers("DetectedIssue", &["author"]),
    gathers("DeviceAssociation", &["device"]),
    gathers("DeviceComponent", &["source"]),
    gathers("DeviceMetric", &["source"]),
    gathers("DeviceRequest", &["device", "performer", "requester", "subject"]),
    gathers("DeviceUseStatement", &["device"]),
    gathers("DiagnosticReport", &["subject"]),
    gathers("DocumentManifest", &["author", "subject"]),
    gathers("DocumentReference", &["author", "subject"]),
    gathers("ExplanationOfBenefit", &["detail-udi", "item-udi", "procedure-udi", "subdetail-udi"]),
    gathers("Flag", &["author"]),
    gathers("Group", &["member"]),
    gathers("ImagingManifest", &["author"]),
    gathers("Invoice", &["participant"]),
    gathers("List", &["source", "subject"]),
    gathers("Media", &["subject"]),
    gathers("MedicationAdministration", &["device"]),
    gathers("MessageHeader", &["target"]),
    gathers("Observation", &["device", "subject"]),
    gathers("ProcedureRequest", &["performer", "requester"]),
    gathers("Provenance", &["agent"]),
    gathers("QuestionnaireResponse", &["author"]),
    gathers("RequestGroup", &["author"]),
    gathers("RequestOrchestration", &["author"]),
    gathers("ResearchSubject", &["subject"]),
    gathers("RiskAssessment", &["performer"]),
    gathers("Schedule", &["actor"]),
    gathers("ServiceRequest", &["performer", "requester"]),
    gathers("Specimen", &["subject"]),
    gathers("SupplyRequest", &["requester"]),
];

const DEFS: &[CompartmentDef] = &[
    CompartmentDef { code: "Patient", members: PATIENT },
    CompartmentDef { code: "Encounter", members: ENCOUNTER },
    CompartmentDef { code: "RelatedPerson", members: RELATEDPERSON },
    CompartmentDef { code: "Practitioner", members: PRACTITIONER },
    CompartmentDef { code: "Device", members: DEVICE },
];
