












use fhir_core::{Error, FhirVersion};
use serde_json::Value;
use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;


const CODES: [&str; 5] = [
    "Patient",
    "Encounter",
    "RelatedPerson",
    "Practitioner",
    "Device",
];

fn artifact(directory: &Path, version: FhirVersion) -> std::path::PathBuf {
    directory.join(format!("{}-profiles-resources.json", version.as_str()))
}



pub fn read(
    directory: &Path,
) -> Result<BTreeMap<String, BTreeMap<String, BTreeSet<String>>>, Error> {
    let mut held: BTreeMap<String, BTreeMap<String, BTreeSet<String>>> = BTreeMap::new();
    for version in FhirVersion::ALL {
        let path = artifact(directory, version);
        let text = std::fs::read_to_string(&path).map_err(|error| {
            Error::Config(format!("{} cannot be read: {error}", path.display()))
        })?;
        let body: Value =
            serde_json::from_str(&text).map_err(|error| Error::InvalidJson(error.to_string()))?;
        let entries = body
            .get("entry")
            .and_then(Value::as_array)
            .ok_or_else(|| Error::Config(format!("{} carries no entry", path.display())))?;
        for entry in entries {
            let resource = &entry["resource"];
            if resource["resourceType"] != "CompartmentDefinition" {
                continue;
            }
            let Some(code) = resource["code"].as_str() else {
                continue;
            };
            let members = held.entry(code.to_owned()).or_default();
            for member in resource["resource"].as_array().into_iter().flatten() {
                let Some(named) = member["code"].as_str() else {
                    continue;
                };
                let params: BTreeSet<String> = member["param"]
                    .as_array()
                    .into_iter()
                    .flatten()
                    .filter_map(Value::as_str)
                    .filter(|param| !param.contains(['{', '}']))
                    .map(str::to_owned)
                    .collect();
                if params.is_empty() {
                    continue;
                }
                members.entry(named.to_owned()).or_default().extend(params);
            }
        }
    }
    if held.is_empty() {
        return Err(Error::Config(
            "the artifacts carry no compartment definition".to_owned(),
        ));
    }
    Ok(held)
}



pub fn source(held: &BTreeMap<String, BTreeMap<String, BTreeSet<String>>>) -> String {
    let mut text = String::new();
    text.push_str("// Generated by `compartments`; do not edit by hand.\n");
    text.push_str("// Source: the CompartmentDefinition resources published for each served\n");
    text.push_str("// release, unioned. Regenerate with:\n");
    text.push_str("//   compartments <artifacts> crates/core/src/search/compartments.rs\n\n");
    for code in CODES {
        let Some(members) = held.get(code) else {
            continue;
        };
        text.push_str(&format!(
            "const {}: &[Membership] = &[\n",
            code.to_uppercase()
        ));
        text.push_str(&format!(
            "    itself(\"{code}\", &[{}]),\n",
            members.get(code).map(quoted).unwrap_or_default()
        ));
        for (named, params) in members {
            if named == code {
                continue;
            }
            text.push_str(&format!(
                "    gathers(\"{named}\", &[{}]),\n",
                quoted(params)
            ));
        }
        text.push_str("];\n\n");
    }
    text.push_str("const DEFS: &[CompartmentDef] = &[\n");
    for code in CODES {
        if !held.contains_key(code) {
            continue;
        }
        text.push_str(&format!(
            "    CompartmentDef {{ code: \"{code}\", members: {} }},\n",
            code.to_uppercase()
        ));
    }
    text.push_str("];\n");
    text
}

fn quoted(params: &BTreeSet<String>) -> String {
    params
        .iter()
        .map(|param| format!("\"{param}\""))
        .collect::<Vec<String>>()
        .join(", ")
}
