[package]
name = "fhir-adapter-relational"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
flate2 = "1"
serde_json = "1"
fhir-core = { path = "../core" }
fhir-store = { path = "../store" }
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio", "postgres"] }
tokio = { version = "1", features = ["macros", "rt", "sync", "time"] }

[dev-dependencies]
fhir-store-contract = { path = "../contract" }
fhir-store = { path = "../store" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
