name: ci

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: format
        run: cargo fmt --all --check
      - name: analysis
        run: cargo clippy --workspace --all-targets -- -D warnings
      - name: build
        run: cargo build --workspace
      - name: engines
        run: docker compose up -d --wait
      - name: test
        run: cargo test --workspace
      - name: engines down
        if: always()
        run: docker compose down -v
